const langObject = {
    en: {
      quote: 'js/enquotes.json',
      langEn: 'English',
      langRu: 'Russian',
      settings: 'Settings',
      changeLang: 'Language',
      widget: 'Widgets',
      time: 'Time',
      date: 'Date',
      weather: 'Weather',
      greeting: 'Greeting',
      quoteTitle: 'Quote',
      player: 'Audio Player',
      logo: 'Logo',
      todo: 'ToDo List',
      gallery: 'Background image',
      wind: 'Wind speed',
      windMs: 'm/s',
      humidity: 'Humidity ',
      notFound: 'Error! City not found!',
      cantFind: "Error! Can't find the weather for ",
      placeholder: '[Enter your name]',
      placeholderCity: '[Enter city]',
      placeholderTodo: 'Add new task...',
      placeholderTags: 'Select theme...',
      defaultCity: 'Minsk',
      morning: 'Good morning,',
      day: 'Good afternoon,',
      evening: 'Good evening,',
      night: 'Good night,',
      locale: 'en-GB',
      addBtn: 'Add',
      /*tag: '[Enter tag for search]',*/
    },
    ru: {
      quote: 'js/ruquotes.json',
      langEn: 'Английский',
      langRu: 'Русский',
      settings: 'Настройки',
      changeLang: 'Язык',
      widget: 'Виджеты',
      time: 'Время',
      date: 'Дата',
      weather: 'Погода',
      greeting: 'Приветствие',
      quoteTitle: 'Цитата',
      player: 'Аудиоплеер',
      logo: 'Логотип',
      todo: 'Список дел',
      gallery: 'Фоновое изображение',
      wind: 'Скорость ветра',
      windMs: 'м/с',
      humidity: 'Влажность ',
      notFound: 'Ошибка! Город не найден!',
      cantFind: 'Ошибка! Не могу найти погоду для ',
      placeholder: '[Введите ваше имя]',
      placeholderCity: '[Введите город]',
      placeholderTodo: 'Добавить задачу...',
      placeholderTags: 'Выбрать тему...',
      defaultCity: 'Минск',
      morning: 'Доброе утро,',
      day: 'Добрый день,',
      evening: 'Добрый вечер,',
      night: 'Доброй ночи,',
      locale: 'ru-RU',
      addBtn: 'Добавить',
      /*tag: '[Введите тег для поиска]',*/
    }
  }

  
  export default langObject;